/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.studyplanner.view;

import com.studyplanner.controller.UserController; 
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author Sandeep
 */
public class LoginView extends javax.swing.JFrame {
    
    // 1. Declare Variables
    private final UserController userController;
    private CardLayout cardLayout;

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        
        // 2. Initialize Controller
        userController = new UserController();

        // 3. Setup Layout
        // We look for the CardLayout on the container 'mainCardPanel'
        if (mainCardPanel.getLayout() instanceof CardLayout) {
            cardLayout = (CardLayout) mainCardPanel.getLayout();
        } else {
            System.err.println("Error: mainCardPanel is not set to CardLayout in Design View!");
        }
        
        // 4. Center the window on screen
        this.setLocationRelativeTo(null);
        
        // 5. Clear the default "jTextField1" text if it exists
        txtLoginUser.setText("");
        txtLoginPass.setText("");
        txtSignupUser.setText("");
        txtSignupPass.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainCardPanel = new javax.swing.JPanel();
        pnlLogin = new javax.swing.JPanel();
        label9 = new java.awt.Label();
        username = new java.awt.Label();
        password = new java.awt.Label();
        txtLoginUser = new javax.swing.JTextField();
        txtLoginPass = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        label13 = new java.awt.Label();
        aSignup = new javax.swing.JButton();
        pnlSignup = new javax.swing.JPanel();
        label10 = new java.awt.Label();
        signupUsername = new java.awt.Label();
        signupPassword = new java.awt.Label();
        txtSignupUser = new javax.swing.JTextField();
        txtSignupPass = new javax.swing.JTextField();
        btnSignup = new javax.swing.JButton();
        label16 = new java.awt.Label();
        aLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mainCardPanel");

        mainCardPanel.setLayout(new java.awt.CardLayout());

        pnlLogin.setBackground(new java.awt.Color(31, 31, 48));

        label9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        label9.setForeground(new java.awt.Color(255, 255, 255));
        label9.setText("GyanYogana Login");

        username.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setText("Username:");

        password.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setText("Password:");

        txtLoginUser.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtLoginUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        txtLoginPass.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtLoginPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        btnLogin.setBackground(new java.awt.Color(88, 101, 242));
        btnLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnLogin.addActionListener(this::btnLoginActionPerformed);

        label13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label13.setForeground(new java.awt.Color(255, 255, 255));
        label13.setText("Please sign in to continue");
        label13.setVisible(false);

        aSignup.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        aSignup.setForeground(new java.awt.Color(255, 255, 255));
        aSignup.setText("Don't have an account? Sign Up");
        aSignup.setActionCommand("");
        aSignup.setContentAreaFilled(false);
        aSignup.addActionListener(this::aSignupActionPerformed);

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLoginUser)
                                .addComponent(txtLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(aSignup))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlLoginLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtLoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aSignup)
                .addGap(70, 70, 70))
        );

        mainCardPanel.add(pnlLogin, "cardLogin");

        pnlSignup.setBackground(new java.awt.Color(31, 31, 48));

        label10.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        label10.setForeground(new java.awt.Color(255, 255, 255));
        label10.setText("Create Account");

        signupUsername.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        signupUsername.setForeground(new java.awt.Color(255, 255, 255));
        signupUsername.setText("Username:");

        signupPassword.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        signupPassword.setForeground(new java.awt.Color(255, 255, 255));
        signupPassword.setText("Password:");

        txtSignupUser.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtSignupUser.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        txtSignupPass.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        txtSignupPass.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        btnSignup.setBackground(new java.awt.Color(88, 101, 242));
        btnSignup.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnSignup.setForeground(new java.awt.Color(255, 255, 255));
        btnSignup.setText("Sign Up");
        btnSignup.setActionCommand("Signup");
        btnSignup.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        btnSignup.addActionListener(this::btnSignupActionPerformed);

        label16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        label16.setForeground(new java.awt.Color(255, 255, 255));
        label16.setText("Please sign in to continue");
        label16.setVisible(false);

        aLogin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        aLogin.setForeground(new java.awt.Color(255, 255, 255));
        aLogin.setText("Already have an account? Login");
        aLogin.setActionCommand("");
        aLogin.setContentAreaFilled(false);
        aLogin.addActionListener(this::aLoginActionPerformed);

        javax.swing.GroupLayout pnlSignupLayout = new javax.swing.GroupLayout(pnlSignup);
        pnlSignup.setLayout(pnlSignupLayout);
        pnlSignupLayout.setHorizontalGroup(
            pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignupLayout.createSequentialGroup()
                .addGroup(pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSignupLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSignup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(signupUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(signupPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSignupUser)
                                .addComponent(txtSignupPass, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSignupLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(aLogin)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        pnlSignupLayout.setVerticalGroup(
            pnlSignupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSignupLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(signupUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSignupUser, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signupPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSignupPass, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnSignup, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aLogin)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        mainCardPanel.add(pnlSignup, "cardSignup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        //Get Data
        String user = txtLoginUser.getText();
        String pass = txtLoginPass.getText();

        if (user.trim().isEmpty() || pass.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter Username and Password.");
            return;
        }

        if (userController.loginUser(user, pass)) {
            JOptionPane.showMessageDialog(this, "Login Successful!");
            
            // Open Dashboard
            new DashboardUI().setVisible(true); 
            
            // Close Login Window
            SwingUtilities.getWindowAncestor(this).dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Invalid Username or Password.");
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void aSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSignupActionPerformed
        // User clicked "Don't have an account?"
        if (cardLayout != null) {
            cardLayout.show(mainCardPanel, "cardSignup");
        }
    }//GEN-LAST:event_aSignupActionPerformed

    private void btnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignupActionPerformed
        // 1. Get Data
        String user = txtSignupUser.getText();
        String pass = txtSignupPass.getText();

        if (user.trim().isEmpty() || pass.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return;
        }

        if (userController.registerUser(user, pass)) {
            JOptionPane.showMessageDialog(this, "Account Created! Please Login.");
            
            // Clear fields
            txtSignupUser.setText("");
            txtSignupPass.setText("");

            // Switch to Login Card
            if (cardLayout != null) {
                cardLayout.show(mainCardPanel, "cardLogin");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Username already exists.");
        }
    }//GEN-LAST:event_btnSignupActionPerformed

    private void aLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aLoginActionPerformed
        // User clicked "Already have an account?"
        if (cardLayout != null) {
            cardLayout.show(mainCardPanel, "cardLogin");
        }
    }//GEN-LAST:event_aLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aLogin;
    private javax.swing.JButton aSignup;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignup;
    private java.awt.Label label10;
    private java.awt.Label label13;
    private java.awt.Label label16;
    private java.awt.Label label9;
    private javax.swing.JPanel mainCardPanel;
    private java.awt.Label password;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlSignup;
    private java.awt.Label signupPassword;
    private java.awt.Label signupUsername;
    private javax.swing.JTextField txtLoginPass;
    private javax.swing.JTextField txtLoginUser;
    private javax.swing.JTextField txtSignupPass;
    private javax.swing.JTextField txtSignupUser;
    private java.awt.Label username;
    // End of variables declaration//GEN-END:variables
}
